<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{


	public function getActivePosts()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('p');

		$qb->from(Post::class, 'p')
			->andWhere($qb->expr()->eq('p.active', TRUE))
			->orderBy('p.date', 'DESC');

		return $qb->getQuery()->getResult();
	}

}
